# this file contains links crawled by the app

clothing:
  aritzia:
    sweater: http://www.aritzia.com/en/clothing/sweaters?lastViewed=1000


skincare:
  faceshop:
      home: https://thefaceshop.ca/en/